# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

JFROG failed task :
- task: JfrogCliV2@1
  displayName: 'Configure dotnet'
  env:
    JFROG_CLI_LOG_LEVEL: DEBUG
  inputs:
    # msbuildArgs: /p:RunWixToolsOutOfProc=true
    jfrogPlatformConnection: new
    # workingDirectory: 'c:/Program Files (x86)/WiX Toolset v3.11/bin'
    command: |
      jf dotnetc --repo-resolve=hello
      jf dotnet restore GatewaySetup\Gateway.sln --build-name="IConnectGW-Build" --build-number=1 --project hi --module=dotnet

